config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lift_sets
  resources :routine_lifts
  resources :routines
  root 'pages#home'
  resources :workouts
  resources :lift_workouts
  resources :lifts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lift.rb
class Lift < ApplicationRecord
  has_many :lift_workouts
end

app/models/lift_set.rb
class LiftSet < ApplicationRecord
  belongs_to :lift_workout
end

app/models/lift_workout.rb
class LiftWorkout < ApplicationRecord
  belongs_to :workout
  belongs_to :lift
  has_many :lift_sets, dependent: :destroy

  accepts_nested_attributes_for :lift_sets

  def formatted_weight
    "#{weight}lb" if weight
  end

  def formatted_reps
    lift_sets.map{|ls| ls.rep_count || '-' }.join('/')
  end

  private

end

app/models/routine.rb
class Routine < ApplicationRecord
  has_many :routine_lifts
  has_many :workouts
end

app/models/routine_lift.rb
class RoutineLift < ApplicationRecord
  belongs_to :lift
  belongs_to :routine
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :routine, optional: true
  has_many :lift_workouts, dependent: :destroy

  accepts_nested_attributes_for :lift_workouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lift_sets_controller.rb
class LiftSetsController < ApplicationController
  before_action :set_lift_set, only: [:show, :edit, :update, :destroy]

  def index
    @lift_sets = LiftSet.all
  end

  def new
    @lift_set = LiftSet.new
  end

  def edit
  end

  def create
    @lift_set = LiftSet.new(lift_set_params)

    if @lift_set.save
      redirect_to @lift_set, notice: 'Lift set was successfully created.'
    else
      render :new
    end
  end

  def update
    if @lift_set.update(lift_set_params)
      redirect_to @lift_set, notice: 'Lift set was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lift_set.destroy
    redirect_to lift_sets_url, notice: 'Lift set was successfully destroyed.'
  end

  private
    def set_lift_set
      @lift_set = LiftSet.find(params[:id])
    end

    def lift_set_params
      params.require(:lift_set).permit(:rep_count, :lift_workout_id)
    end
end

app/controllers/lift_workouts_controller.rb
class LiftWorkoutsController < ApplicationController
  before_action :set_lift_workout, only: [:show, :edit, :update, :destroy]

  def index
    @lift_workouts = LiftWorkout.all
  end

  def new
    @lift_workout = LiftWorkout.new
  end

  def edit
  end

  def create
    @lift_workout = LiftWorkout.new(lift_workout_params)

    if @lift_workout.save
      redirect_to @lift_workout, notice: 'Lift workout was successfully created.'
    else
      render :new
    end
  end

  def update
    if @lift_workout.update(lift_workout_params)
      redirect_to @lift_workout, notice: 'Lift workout was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lift_workout.destroy
    redirect_to lift_workouts_url, notice: 'Lift workout was successfully destroyed.'
  end

  private
    def set_lift_workout
      @lift_workout = LiftWorkout.find(params[:id])
    end

    def lift_workout_params
      params.require(:lift_workout).permit(:weight, :workout_id, :lift_id)
    end
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
  before_action :set_lift, only: [:show, :edit, :update, :destroy]

  def index
    @lifts = Lift.all
  end

  def show
  end

  def new
    @lift = Lift.new
  end

  def edit
  end

  def create
    @lift = Lift.new(lift_params)

    if @lift.save
      redirect_to @lift, notice: 'Lift was successfully created.'
    else
      render :new
    end
  end

  def update
    if @lift.update(lift_params)
      redirect_to @lift, notice: 'Lift was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lift.destroy
    redirect_to lifts_url, notice: 'Lift was successfully destroyed.'
  end

  private
    def set_lift
      @lift = Lift.find(params[:id])
    end

    def lift_params
      params.require(:lift).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @workouts = Workout.order(workout_date: :desc).first(2)
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: [:show, :edit, :update, :destroy]

  # GET /routines
  def index
    @routines = Routine.all
  end

  # GET /routines/1
  def show
  end

  # GET /routines/new
  def new
    @routine = Routine.new
  end

  # GET /routines/1/edit
  def edit
  end

  # POST /routines
  def create
    @routine = Routine.new(routine_params)

    if @routine.save
      redirect_to @routine, notice: 'Routine was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /routines/1
  def update
    if @routine.update(routine_params)
      redirect_to @routine, notice: 'Routine was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /routines/1
  def destroy
    @routine.destroy
    redirect_to routines_url, notice: 'Routine was successfully destroyed.'
  end

  private
    def set_routine
      @routine = Routine.find(params[:id])
    end

    def routine_params
      params.require(:routine).permit(:name)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index] # fix this

  def index
    @workouts = Workout.includes(
      lift_workouts: [
        :lift,
        :lift_sets
      ]
    ).order(workout_date: :desc)
  end

  def show
  end

  def new
    @workout = Workout.new(routine_id: params[:routine])
    build_workout_sets
  end

  def edit
  end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      redirect_to workouts_url
    else
      render :new
    end
  end

  def update
    if @workout.update(workout_params)
      redirect_to edit_workout_url
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
    redirect_to workouts_url, notice: 'Workout was successfully destroyed.'
  end

  private
    def set_workout
      @workout = Workout.includes(
        lift_workouts: [
          :lift,
          :lift_sets
        ]
      ).order('lift_sets.created_at').find(params[:id])
    end

    def build_workout_sets
      @routine = @workout.routine
      @routine&.routine_lifts&.each do |routine_lift|
        lift_workout = @workout.lift_workouts.build(
          lift_id: routine_lift.lift_id,
          rep_count: routine_lift.rep_count
        )
        routine_lift.set_count.times { lift_workout.lift_sets.build }
      end
    end

    def workout_params
      params.require(:workout).permit(
        :body_weight,
        :rep_counts,
        :workout_date,
        :lift_workouts_attributes => [
          :id,
          :weight,
          :rep_count,
          :lift_id,
          :lift_sets_attributes => [
            :id,
            :rep_count
          ]
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lift_sets_helper.rb
module LiftSetsHelper
end

app/helpers/lift_workouts_helper.rb
module LiftWorkoutsHelper
end

app/helpers/lifts_helper.rb
module LiftsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/routine_lifts_helper.rb
module RoutineLiftsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def workout_date_detail(date)
    today_or_yesterday(date) || date.strftime("%a, %d %b")
  end

  def workout_date_day(date)
    today_or_yesterday(date) || date.strftime("%a")
  end

  def workout_date_short(date)
    date.strftime("%d %b")
  end

  def today_or_yesterday(date)
    if date == Date.today
      'Today'
    elsif date == Date.yesterday
      'Yesterday'
    end
  end
end

app/views/lift_sets/_form.html.erb
<%= form_with(model: lift_set, local: true) do |form| %>
  <% if lift_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lift_set.errors.count, "error") %> prohibited this lift_set from being saved:</h2>

      <ul>
        <% lift_set.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rep_count %>
    <%= form.number_field :rep_count %>
  </div>

  <div class="field">
    <%= form.label :lift_workout_id %>
    <%= form.text_field :lift_workout_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lift_sets/edit.html.erb
<h1>Editing Lift Set</h1>

<%= render 'form', lift_set: @lift_set %>

<%= link_to 'Show', @lift_set %> |
<%= link_to 'Back', lift_sets_path %>

app/views/lift_sets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lift Sets</h1>

<table>
  <thead>
    <tr>
      <th>Rep count</th>
      <th>Lift workout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lift_sets.each do |lift_set| %>
      <tr>
        <td><%= lift_set.rep_count %></td>
        <td><%= lift_set.lift_workout_id %></td>
        <td><%= link_to 'Show', lift_set %></td>
        <td><%= link_to 'Edit', edit_lift_set_path(lift_set) %></td>
        <td><%= link_to 'Destroy', lift_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lift Set', new_lift_set_path %>

app/views/lift_sets/new.html.erb
<h1>New Lift Set</h1>

<%= render 'form', lift_set: @lift_set %>

<%= link_to 'Back', lift_sets_path %>

app/views/lift_workouts/_form.html.erb
<%= form_with(model: lift_workout, local: true) do |form| %>
  <% if lift_workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lift_workout.errors.count, "error") %> prohibited this lift_workout from being saved:</h2>

      <ul>
        <% lift_workout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :workout_id %>
    <%= form.text_field :workout_id %>
  </div>

  <div class="field">
    <%= form.label :lift_id %>
    <%= form.text_field :lift_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lift_workouts/edit.html.erb
<h1>Editing Lift Workout</h1>

<%= render 'form', lift_workout: @lift_workout %>

<%= link_to 'Show', @lift_workout %> |
<%= link_to 'Back', lift_workouts_path %>

app/views/lift_workouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lift Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Workout</th>
      <th>Lift</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lift_workouts.each do |lift_workout| %>
      <tr>
        <td><%= lift_workout.weight %></td>
        <td><%= lift_workout.workout_id %></td>
        <td><%= lift_workout.lift_id %></td>
        <td><%= link_to 'Show', lift_workout %></td>
        <td><%= link_to 'Edit', edit_lift_workout_path(lift_workout) %></td>
        <td><%= link_to 'Destroy', lift_workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lift Workout', new_lift_workout_path %>

app/views/lift_workouts/new.html.erb
<h1>New Lift Workout</h1>

<%= render 'form', lift_workout: @lift_workout %>

<%= link_to 'Back', lift_workouts_path %>

app/views/lifts/_form.html.erb
<%= form_with(model: lift, local: true) do |form| %>
  <% if lift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lift.errors.count, "error") %> prohibited this lift from being saved:</h2>

      <ul>
        <% lift.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lifts/edit.html.erb
<h1>Editing Lift</h1>

<%= render 'form', lift: @lift %>

<%= link_to 'Show', @lift %> |
<%= link_to 'Back', lifts_path %>

app/views/lifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lifts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lifts.each do |lift| %>
      <tr>
        <td><%= lift.name %></td>
        <td><%= link_to 'Show', lift %></td>
        <td><%= link_to 'Edit', edit_lift_path(lift) %></td>
        <td><%= link_to 'Destroy', lift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lift', new_lift_path %>

app/views/lifts/new.html.erb
<h1>New Lift</h1>

<%= render 'form', lift: @lift %>

<%= link_to 'Back', lifts_path %>

app/views/lifts/show.html.erb
<!-- we can put lift data here down the road -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lift.name %>
</p>

<%= link_to 'Edit', edit_lift_path(@lift) %> |
<%= link_to 'Back', lifts_path %>

app/views/routines/_form.html.erb
<%= form_with(model: routine, local: true) do |form| %>
  <% if routine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(routine.errors.count, "error") %> prohibited this routine from being saved:</h2>

      <ul>
        <% routine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routines/edit.html.erb
<h1>Editing Routine</h1>

<%= render 'form', routine: @routine %>

<%= link_to 'Show', @routine %> |
<%= link_to 'Back', routines_path %>

app/views/routines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routines.each do |routine| %>
      <tr>
        <td><%= routine.name %></td>
        <td><%= link_to 'Show', routine %></td>
        <td><%= link_to 'Edit', edit_routine_path(routine) %></td>
        <td><%= link_to 'Destroy', routine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Routine', new_routine_path %>

app/views/routines/new.html.erb
<h1>New Routine</h1>

<%= render 'form', routine: @routine %>

<%= link_to 'Back', routines_path %>

app/views/workouts/_form.html.erb
<%= javascript_pack_tag "workouts/form" %>

<%= form_with(model: workout, local: true) do |form| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :lift_workouts do |lw| %>
    <div class="form-group">
      <%= lw.object&.lift&.name || 'Click to set lift' %>
      <%= lw.number_field :weight, placeholder: "Add lift_workout weight", class: "form-control" %>
      <%= lw.hidden_field :lift_id %>
      <%= lw.hidden_field :rep_count %>
      <div data-max-reps="<%= lw.object.rep_count %>">
        <%= lw.fields_for :lift_sets do |ls| %>
          <button class="btn btn-primary rep_count_button" type="button"><%= ls.object.rep_count || '-' %></button>
          <%= ls.hidden_field :rep_count, class: "form-control" %>
        <% end %>
      </div>
      <hr>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body_weight %>
    <%= form.number_field :body_weight %>
  </div>

  <%= form.hidden_field :workout_date, value: @workout.workout_date || Date.today %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workouts/_lift_workout.html.erb
<div class="card col">
  <div class="card-body py-5">
    <h5 class="mb-3"><%= lift_workout.lift.name %></h5>
    <h6 class="mb-3"><%= lift_workout.formatted_reps %></h6>
    <h6><%= lift_workout.formatted_weight %></h6>
  </div>
</div>

app/views/workouts/_workout.html.erb
<div class="d-flex row">
  <div class="card col">
    <div class="card-body py-5">
      <h5 class="mb-3"><%= workout_date_day(workout.workout_date) %></h5>
      <h6 class="mb-3"><%= workout_date_short(workout.workout_date) %></h6>
      <%= link_to 'Edit', edit_workout_path(workout) %>
    </div>
  </div>
  <%= render partial: 'lift_workout', collection: workout.lift_workouts %>
</div>

app/views/workouts/edit.html.erb
<h1 class="display-1"><%= workout_date_detail(@workout.workout_date) %></h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<%= javascript_pack_tag "workouts/index_page" %>

<p id="notice"><%= notice %></p>

<h1 class="display-1">History</h1>

<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

<%= button_to 'Home', root_url, :class => "btn btn-secondary", :method => :get  %>

<%= button_to 'New Workout', new_workout_path, :class => "btn btn-primary", :method => :get  %>

<div class="container-fluid">
  <%= render partial: 'workout', collection: @workouts %>
</div>

app/views/workouts/new.html.erb
<h1 class="display-1">New Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<h1>WORKOUT DETAIL (show)</h1>
<h2>Do this after edit</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Body weight:</strong>
  <%= @workout.body_weight %>
</p>

<% @workout.lift_workouts.each do |lift_workout| %>
  <div>Lift Name: <%= lift_workout.lift.name %> -
    Lift Weight: <%= lift_workout.weight %></div>
    <% lift_workout.rep_count.each do |reps| %>
      <div><%= reps %></div>

    <% end %>
<% end %>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>