config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lift_sets
  resources :routine_lifts
  resources :routines
  root 'pages#home'
  resources :workouts
  resources :lift_workouts
  resources :lifts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lift.rb
class Lift < ApplicationRecord
  has_many :lift_workouts
end

app/models/lift_set.rb
class LiftSet < ApplicationRecord
  belongs_to :lift_workout
end

app/models/lift_workout.rb
class LiftWorkout < ApplicationRecord
  belongs_to :workout
  belongs_to :lift
  has_many :lift_sets, dependent: :destroy

  accepts_nested_attributes_for :lift_sets

  def formatted_weight
    "#{weight}lb" if weight
  end

  def formatted_reps
    lift_sets.map{|ls| ls.rep_count || '-' }.join('/')
  end

  private

end

app/models/routine.rb
class Routine < ApplicationRecord
  has_many :routine_lifts
  has_many :workouts
end

app/models/routine_lift.rb
class RoutineLift < ApplicationRecord
  belongs_to :lift
  belongs_to :routine
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :routine, optional: true
  has_many :lift_workouts, dependent: :destroy

  accepts_nested_attributes_for :lift_workouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lift_sets_controller.rb
class LiftSetsController < ApplicationController
  before_action :set_lift_set, only: [:show, :edit, :update, :destroy]

  def index
    @lift_sets = LiftSet.all
  end

  def new
    @lift_set = LiftSet.new
  end

  def edit
  end

  def create
    @lift_set = LiftSet.new(lift_set_params)

    if @lift_set.save
      redirect_to @lift_set, notice: 'Lift set was successfully created.'
    else
      render :new
    end
  end

  def update
    if @lift_set.update(lift_set_params)
      redirect_to @lift_set, notice: 'Lift set was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lift_set.destroy
    redirect_to lift_sets_url, notice: 'Lift set was successfully destroyed.'
  end

  private
    def set_lift_set
      @lift_set = LiftSet.find(params[:id])
    end

    def lift_set_params
      params.require(:lift_set).permit(:rep_count, :lift_workout_id)
    end
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
  before_action :set_lift, only: [:show, :edit, :update, :destroy]

  def index
    @lifts = Lift.all
  end

  def show
  end

  def new
    @lift = Lift.new
  end

  def edit
  end

  def create
    @lift = Lift.new(lift_params)

    if @lift.save
      redirect_to @lift, notice: 'Lift was successfully created.'
    else
      render :new
    end
  end

  def update
    if @lift.update(lift_params)
      redirect_to @lift, notice: 'Lift was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lift.destroy
    redirect_to lifts_url, notice: 'Lift was successfully destroyed.'
  end

  private
    def set_lift
      @lift = Lift.find(params[:id])
    end

    def lift_params
      params.require(:lift).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @workouts = Workout.order(workout_date: :desc).first(2)
  end
end

app/controllers/routine_lifts_controller.rb
class RoutineLiftsController < ApplicationController
  before_action :set_routine_lift, only: [:show, :edit, :update, :destroy]

  def index
    @routine_lifts = RoutineLift.all
  end

  def show
  end

  def new
    @routine_lift = RoutineLift.new
  end

  def edit
  end

  def create
    @routine_lift = RoutineLift.new(routine_lift_params)

    if @routine_lift.save
      redirect_to @routine_lift, notice: 'Routine lift was successfully created.'
    else
      render :new
    end
  end

  def update
    if @routine_lift.update(routine_lift_params)
      redirect_to @routine_lift, notice: 'Routine lift was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @routine_lift.destroy
    redirect_to routine_lifts_url, notice: 'Routine lift was successfully destroyed.'
  end

  private
    def set_routine_lift
      @routine_lift = RoutineLift.find(params[:id])
    end

    def routine_lift_params
      params.require(:routine_lift).permit(:rep_count, :set_count, :routine_id, :lift_id)
    end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: [:show, :edit, :update, :destroy]

  # GET /routines
  def index
    @routines = Routine.all
  end

  # GET /routines/1
  def show
  end

  # GET /routines/new
  def new
    @routine = Routine.new
  end

  # GET /routines/1/edit
  def edit
  end

  # POST /routines
  def create
    @routine = Routine.new(routine_params)

    if @routine.save
      redirect_to @routine, notice: 'Routine was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /routines/1
  def update
    if @routine.update(routine_params)
      redirect_to @routine, notice: 'Routine was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /routines/1
  def destroy
    @routine.destroy
    redirect_to routines_url, notice: 'Routine was successfully destroyed.'
  end

  private
    def set_routine
      @routine = Routine.find(params[:id])
    end

    def routine_params
      params.require(:routine).permit(:name)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index] # fix this

  def index
    @workouts = Workout.includes(
      lift_workouts: [
        :lift,
        :lift_sets
      ]
    ).order(workout_date: :desc)
  end

  def show
  end

  def new
    @workout = Workout.new(routine_id: params[:routine])
    build_workout_sets
  end

  def edit
  end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      redirect_to workouts_url
    else
      render :new
    end
  end

  def update
    if @workout.update(workout_params)
      redirect_to edit_workout_url
    else
      render :edit
    end
  end

  def destroy
    @workout.destroy
    redirect_to workouts_url, notice: 'Workout was successfully destroyed.'
  end

  private
    def set_workout
      @workout = Workout.includes(
        lift_workouts: [
          :lift,
          :lift_sets
        ]
      ).order('lift_sets.created_at').find(params[:id])
    end

    def build_workout_sets
      @routine = @workout.routine
      @routine&.routine_lifts&.each do |routine_lift|
        lift_workout = @workout.lift_workouts.build(
          lift_id: routine_lift.lift_id,
          rep_count: routine_lift.rep_count
        )
        routine_lift.set_count.times { lift_workout.lift_sets.build }
      end
    end

    def workout_params
      params.require(:workout).permit(
        :body_weight,
        :rep_counts,
        :workout_date,
        :lift_workouts_attributes => [
          :id,
          :weight,
          :rep_count,
          :lift_id,
          :lift_sets_attributes => [
            :id,
            :rep_count
          ]
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lift_sets_helper.rb
module LiftSetsHelper
end

app/helpers/lift_workouts_helper.rb
module LiftWorkoutsHelper
end

app/helpers/lifts_helper.rb
module LiftsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/routine_lifts_helper.rb
module RoutineLiftsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def workout_date_detail(date)
    today_or_yesterday(date) || date.strftime("%a, %d %b")
  end

  def workout_date_day(date)
    today_or_yesterday(date) || date.strftime("%a")
  end

  def workout_date_short(date)
    date.strftime("%d %b")
  end

  def today_or_yesterday(date)
    if date == Date.today
      'Today'
    elsif date == Date.yesterday
      'Yesterday'
    end
  end
end

app/views/routine_lifts/_form.html.erb
<%= form_with(model: routine_lift, local: true) do |form| %>
  <% if routine_lift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(routine_lift.errors.count, "error") %> prohibited this routine_lift from being saved:</h2>

      <ul>
        <% routine_lift.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rep_count %>
    <%= form.number_field :rep_count %>
  </div>

  <div class="field">
    <%= form.label :set_count %>
    <%= form.number_field :set_count %>
  </div>

  <div class="field">
    <%= form.label :routine_id %>
    <%= form.text_field :routine_id %>
  </div>

  <div class="field">
    <%= form.label :lift_id %>
    <%= form.text_field :lift_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routine_lifts/edit.html.erb
<h1>Editing Routine Lift</h1>

<%= render 'form', routine_lift: @routine_lift %>

<%= link_to 'Show', @routine_lift %> |
<%= link_to 'Back', routine_lifts_path %>

app/views/routine_lifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routine Lifts</h1>

<table>
  <thead>
    <tr>
      <th>Rep count</th>
      <th>Set count</th>
      <th>Routine</th>
      <th>Lift</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routine_lifts.each do |routine_lift| %>
      <tr>
        <td><%= routine_lift.rep_count %></td>
        <td><%= routine_lift.set_count %></td>
        <td><%= routine_lift.routine_id %></td>
        <td><%= routine_lift.lift_id %></td>
        <td><%= link_to 'Show', routine_lift %></td>
        <td><%= link_to 'Edit', edit_routine_lift_path(routine_lift) %></td>
        <td><%= link_to 'Destroy', routine_lift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Routine Lift', new_routine_lift_path %>

app/views/routine_lifts/new.html.erb
<h1>New Routine Lift</h1>

<%= render 'form', routine_lift: @routine_lift %>

<%= link_to 'Back', routine_lifts_path %>